### PR TITLE
Add support for localization

### LINKED ISSUE #28: Support i18n

### PR DESCRIPTION
**Pull request by claudioandre**
Fixes and closes #28 
****

Please, let me know if you need anything else done (I did this only to check how i18n works, I'm affraid I'm not interested in put much effort in it).

image

### CODE REVIEW

**Comment by jwendell** [comment]
Thanks for the initial work on this. I think this is not complete, right? I mean it's not working out of the box, is it?

**Comment by claudioandre** [comment]
Yes it is. 

Well, I haven't added the .mo file (and one have to copy the .mo file to the proper location while installing using github). But all this is done when you release the extension.
- if you mean, that it doesn't work if I do a local (to my home) installation:
  - are you going to accept a compiled .mo file in github?

**Comment by jwendell** [comment]
Yeah, I'm expecting a fully working PR :)

Perhaps this involves the creation of a Makefile to generate those binaries at build time. Take a look at how other extensions do that.

**Comment by claudioandre** [comment]
I failed to find any other extension that has the .mo file. Yes, they use autotools.

**Comment by jwendell** [comment]
https://github.com/jenslody/gnome-shell-extension-openweather is an example.
Just like any other software that uses gettext, you'll likely find only the sources of translations out there (.po files). Binary (.mo) are the result of the building process.

**Comment by claudioandre** [comment]
I added the compiled .mo file. But I guess what you want now it to use autotools to build the extension, and later, add the translation. Is that correct?

**Comment by jwendell** [comment]
Yep, that's correct. If using autotools is the way to achieve our goal, i.e., support translations, then go for it. Having .mo files versioned is not an option.

**Pull request closed without merging**
